export const USERS_LOADED = 'USERS_LOADED';
export const USERROLES_LOADED = 'USERROLES_LOADED';
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const CONTACTS_LOADED = 'CONTACTS_LOADED';
export const STATUSES_LOADED = 'STATUSES_LOADED';
export const CONTACT_LOADED = 'CONTACT_LOADED';
export const CONTACT_LOADING = 'CONTACT_LOADING';
